language: php

php:
  - 5.5
  - 5.6
  - 7.0

sudo: false

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
- phpunit --configuration phpunit.dist.xml
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover
- rm -rf docs/api
- vendor/bin/apigen generate --debug --config apigen.dist.neon
- vendor/bin/phploc src

before_install:
  - rm -rf /temp
  - composer self-update
  - wget https://scrutinizer-ci.com/ocular.phar

after_success:
  - git status
  - git commit -m "Update API"
  - git push


