language: php

php:
  - 7.0

sudo: false

before_install:
  - rm -rf /temp

install:
  - travis_retry composer install --no-interaction --prefer-source
  - composer self-update
  - wget https://scrutinizer-ci.com/ocular.phar

script:
- phpunit --configuration phpunit.dist.xml
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover
- rm -rf docs/api
- vendor/bin/apigen generate --debug --config apigen.dist.neon
- vendor/bin/phploc src




